### PR TITLE
Performance improvements, and minor changes

### PR DESCRIPTION
**Pull request by Byron**
The minor changes are adjustments to how events are handled to make
it a bit more idiomatic.

I did it as part of my "let's look at".

### CODE REVIEW

**Comment by Byron** [comment]
The performance improvements stem from not drawing on every draw event, but only if the game-state state actually changed. This brings the CPU usage down from formerly 16% to 3% on my machine.

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/ixi3dKTVFC4).

_`Looksies #2 [Let's look at piston-tetris]`_

[thumb](https://youtu.be/ixi3dKTVFC4)

**Comment by dunnker** [comment]
Hi Sebastian thanks for looking at the project it was a lot of fun to work on, and I learned a lot about rust and piston, and I really appreciate ideas to improve the project

I am traveling today so I won't be able to look at your commit until tomorrow morning

**Comment by dunnker** [comment]
Thanks again, it plays with very little CPU usage now

**Comment by dunnker** [comment]
FYI, I had to comment one of your changes as it causes an error when I run under Ubuntu:

``` rust
    let window = Glutin_Window::new(
        opengl,
        WindowSettings::new("Piston Tetris", [1024, 768])
                       .exit_on_esc(true)
                       .vsync(true)
                       //TODO causes error on ubuntu
                       //.samples(1)
    );
```

The error is:

thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("glx::ChooseFBConfig failed")', /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:731

**Comment by dunnker** [comment]
Also I increased the updates per second value as it introduced a speed limit on the upper levels. Funny enough, I think a very skilled player could play indefinitely at that speed.

one more thing that's not related to your changes...
as you noted in your youtube video, the code to draw the next tetromino is somewhat duplicated from when you draw the rest of the game board. i'd like to make a general purpose function that could be invoked, but I couldn't figure out what the parameter types for "gl" and "c" would be?

For instance, the draw method takes a closure, with parameters gl and c like so:

``` rust
        self.gl.draw(args.viewport(), |c, gl| {

            self.my_function(c, gl);

        }
```

When I go to write my_function, I can't figure out what the types for c and gl are.
If you happen to know how to write such a function that would be helpful, because as of right now, my draw method is getting quite long, and I'd like to extract out several methods for readability.
Thanks again for your help!

**Comment by Byron** [comment]
You can watch the development stream [on youtube](https://youtu.be/VTyyzeLRlZY).

_`Hacks #2 [tetris-piston - something about types]`_

[thumb](https://youtu.be/VTyyzeLRlZY)

**Comment by Byron** [comment]
Thanks for giving it some more thought and thanks for fixing the arising issues ! Especially the `.samples(...)` setting has proven to not be too portable. Some systems don't seem to support oversampling at all, others can only go to a certain value, like 8.

I tried and think the easiest way to figure out any type is like so:

``` Rust
let () = (c, gl);
```

Cheers

**Comment by dunnker** [comment]
That's a nice trick to figure out the data types; I'm sure I will use that a lot now!
I found a thread on reddit that brings up a similar issue with closures that I was having when trying to refer to "self.tetris" and "self cache" from within the rendering closure:
https://www.reddit.com/r/rust/comments/340c3a/get_the_borrowck_error_when_borrow_self_twice_in/
I've been told on the #rust IRC channel that it is not possible to invoke a method of self from within a closure (possibly only when the closure has captured fields from self?)

It seems the only workaround is to make the callable functions standalone, or part of a static struct.
My latest commit has refactored the rendering to extract out several methods into a static struct called Render. It reads much better now! Thanks for your help!

**Pull request merged**
